# Generated by Django 6.0.5 on 2026-05-29 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ledger',
            index=models.Index(fields=['account', '-created_at'], name='payment_led_account_213987_idx'),
        ),
        migrations.AddIndex(
            model_name='ledger',
            index=models.Index(fields=['transaction_type'], name='payment_led_transac_561935_idx'),
        ),
    ]
